### ISSUE TITLE
Error: Evaluation failed: ReferenceError: nbRolls is not defined

### ISSUE THREAD

**Issue by DmitryShvetsovDA** [drumline18/tb-ring-stats#1]
I try to run it on windows. 
Installed CygWin and npm, defined nbRolls and nbCycles

but when run
$ npm start

it throws an errors:
`50 5
Error: Evaluation failed: ReferenceError: nbRolls is not defined
    at resolve (__puppeteer_evaluation_script__:6:44)
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:5:28

**Comment by drumline18** [comment]
This was developed on a windows only environment. it would probably work in linux too.

It may take a few days for me to be able to lookup my working version. I think this version is just missing passing nbRolls to page.evaluate or something like that.

**Comment by drumline18** [comment]
Actually, I updated it. Delete your folder and try again. it'll give data in json and also some math output in an "analysis" folder once its done running.

And yeah the error was probably just the missing nbRolls as second argument of page.evaluate.

**Comment by DmitryShvetsovDA** [comment]
no errors now. thanks!

**Comment by DmitryShvetsovDA** [comment]
Well, will leave one more comment here:

1) no "analysis" folder created after run finished

2) yep, json wrote according to task description (number, roll, hash, ts...)
But just wondering - is it possible to just receive list of colors randomed?
e.g. I want 100 last rolls - their colors in sequence.

**Comment by drumline18** [comment]
I dont know why the analyzis folder didnt work. This project was re-written to upload rolls to a database in real-time so I'm not really making anything with it anymore.

However if you just want 100 rolls, you can do 1 pass of 100 rolls that'll output the JSON and use the `types` array in the analyzer to get the colors rolled. 2 is gray, 3 is red 5 is blue 50 is yellow.
